### ISSUE TITLE
The code does not want to execute in IDLE

### ISSUE THREAD

**Issue by Kanzll** [laixintao/slic-python-implementation#1]
Hello,
I get some issues to excuting the code, please find the snapshot
Thank you.
<img width="583" alt="capture d ecran 2018-04-08 a 02 27 45" src="https://user-images.githubusercontent.com/16544651/38464037-c1b5f198-3ad4-11e8-8671-f560832ffea7.png">
<img width="579" alt="capture d ecran 2018-04-08 a 02 28 31" src="https://user-images.githubusercontent.com/16544651/38464038-c1c594c2-3ad4-11e8-8ebd-dc9110c7c678.png">

**Comment by laixintao** [comment]
Please install the dependencies.
