### ISSUE TITLE
mistake in slic code

### ISSUE THREAD

**Issue by LuLiCS** [laixintao/slic-python-implementation#3]
hi, I have read your SLIC code and blog, I find a mistake in slic.py Line 88,  I think you should exchange h and w in that line to compute the gradient correctly?

**Comment by ansj11** [comment]
I also find this mistake, so I exchange h and w, then it works

**Comment by laixintao** [comment]
this should be fixed in https://github.com/laixintao/slic-python-implementation/pull/8

plz try the latest version.
