### ISSUE TITLE
代码报错了。请问是什么原因呢？

### ISSUE THREAD

**Issue by yuling9191** [laixintao/slic-python-implementation#6]
gradient = self.data[w + 1][h + 1][0] - self.data[w][h][0] + self.data[w + 1][h + 1][1] - self.data[w][h][1] + self.data[w + 1][h + 1][2] - self.data[w][h][2]
IndexError: index 600 is out of bounds for axis 0 with size 600

**Comment by ak4900** [comment]
宽和高反了

**Comment by laixintao** [comment]
fixed in https://github.com/laixintao/slic-python-implementation/pull/8
