### ISSUE TITLE
search window 2s

### ISSUE THREAD

**Issue by SCccc21** [laixintao/slic-python-implementation#9]
The search window is 2S in paper, but in your code, it seems that you use a window with size 4S. Why is that?

def assignment(self):
        for cluster in self.clusters:
            for h in range(cluster.h - 2 * self.S, cluster.h + 2 * self.S):
                if h < 0 or h >= self.image_height: continue
                for w in range(cluster.w - 2 * self.S, cluster.w + 2 * self.S):
                    if w < 0 or w >= self.image_width: continue
                    L, A, B = self.data[h][w]

**Comment by laixintao** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/9675939/70848702-5c4f4e00-1eb0-11ea-8ca7-902aab9b338b.png">

It said 2S * 2S region, which means 2S for width and 2S for height. As you can see there is only 2 for loop in the pseudo code but there are 3 for-loop in my code, so 2 for-loop *2S means 4S.

I think the code is correct.

**Comment by aiwanaixue** [comment]
原文搜索区域是2S X 2S区域，因此我认为是在每个cluster中心处左/右/上/下各移动 1S 吧？但是源码中，是左/右/上/下各移动 2S ，这样不是导致搜索区域变成4S X 4S吗？ @laixintao

**Comment by laixintao** [comment]
> 原文搜索区域是2S X 2S区域，因此我认为是在每个cluster中心处左/右/上/下各移动 1S 吧？但是源码中，是左/右/上/下各移动 2S ，这样不是导致搜索区域变成4S X 4S吗？ @laixintao

 好像是。可能要移动1s，不过太久了，我也不确定。
